(function(G){'use strict';
const D=G.LEDGER_DATA, $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
if(!D){document.body.innerHTML='<p>data.js를 같은 폴더에 두고 index.html을 다시 열어 주세요.</p>';return}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,mode='number')=>{if(typeof v==='string')return v;if(v===null||v===undefined||!Number.isFinite(v))return '—';if(mode==='pvalue')return v===0?'표현 한계 이하':v<.0001?'< 0.0001':v.toFixed(4);if(mode==='percent')return (v*100).toLocaleString('ko-KR',{maximumFractionDigits:1})+'%';if(mode==='money')return v.toLocaleString('ko-KR',{maximumFractionDigits:0})+'원';return v.toLocaleString('ko-KR',{maximumFractionDigits:4})};
const sum=a=>a.reduce((s,v)=>s+v,0),mean=a=>a.length?sum(a)/a.length:0;
const quantile=(a,q)=>{if(!a.length)return 0;let b=[...a].sort((x,y)=>x-y),p=(b.length-1)*q,i=Math.floor(p);return b[i]+(b[Math.min(i+1,b.length-1)]-b[i])*(p-i)};
const categoryNames=[...new Set(D.catalog.map(m=>m.categoryName))];
const shortCategories=['분포·구조','집단 비교','범주형 관계','회귀모형','시계열','이상거래·유형','검증·보완'];
const statusName={ok:'실행 완료',limited:'조건부 결과',dropped:'제외됨',pending:'대기 중'};
let state={rows:D.rows,results:new Map(),view:'overview',category:-1,search:'',status:'all',period:'day',page:0,running:false,runId:0,lastRun:null,filters:{},logs:[]};
G.DashboardApp={getState:()=>state,run:runAnalyses,showMethod};
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),2800)}
function pill(s){return `<span class="pill ${s}">${statusName[s]||s}</span>`}
function setView(view){state.view=view;$$('.view').forEach(e=>e.classList.toggle('active',e.id==='view-'+view));$$('.nav-item').forEach(e=>e.classList.toggle('active',e.dataset.view===view));const labels={overview:['거래의 흐름을 한눈에.','8,000건의 거래에서 규모, 변화, 그리고 숨은 패턴을 살펴보세요.'],methods:['데이터에 맞는 질문, 96가지.','카드에서 그래프를 바로 비교하고, 클릭해 상세 결과와 해석을 확인하세요.'],data:['결과에서 원본 거래까지.','필터를 적용한 거래와 원본 Excel 행 번호를 확인하세요.'],audit:['분석의 과정도 투명하게.','완료·조건부·제외 상태와 실행 사유를 항목별로 확인하세요.']};$('#view-title').textContent=labels[view][0];$('#view-subtitle').textContent=labels[view][1];if(view==='methods')renderMethods();if(view==='data')renderData();if(view==='audit')renderAudit()}
function getCtx(){return {groupBy:$('#group-filter').value,seed:20261001,dateFrom:$('#date-from').value,dateTo:$('#date-to').value,dataBounds:{min:D.meta.minDate,max:D.meta.maxDate},completeLedger:true}}
function filterRows(){const from=$('#date-from').value,to=$('#date-to').value;if(!from||!to||from>to){toast('시작일과 종료일을 올바르게 입력해 주세요.');return false}state.filters={from,to,type:$('#type-filter').value,department:$('#department-filter').value,payment:$('#payment-filter').value};state.rows=D.rows.filter(r=>r.date>=from&&r.date<=to&&(!state.filters.type||r.type===state.filters.type)&&(!state.filters.department||r.department===state.filters.department)&&(!state.filters.payment||r.payment===state.filters.payment));state.page=0;$('#row-count').textContent=fmt(state.rows.length)+'건';return true}
function countStatuses(){let c={ok:0,limited:0,dropped:0,pending:0};D.catalog.forEach(m=>{let r=state.results.get(m.id);c[r?.status||'pending']++});return c}
function compactMoney(n){return n>=1e8?[(n/1e8).toFixed(2),'억 원']:n>=1e4?[(n/1e4).toLocaleString('ko-KR',{maximumFractionDigits:1}),'만 원']:[n.toLocaleString('ko-KR'),'원']}
function renderKPIs(){const rows=state.rows,sales=rows.filter(r=>r.type==='매출'),purchases=rows.filter(r=>r.type==='매입'),sv=sum(sales.map(r=>r.amount)),pv=sum(purchases.map(r=>r.amount)),vals=rows.map(r=>r.amount),med=quantile(vals,.5);const k=[{label:'매출 거래금액',n:sv,unit:'money',desc:`${fmt(sales.length)}건의 매출 거래`,primary:true,icon:'↗'},{label:'매입 거래금액',n:pv,unit:'money',desc:`${fmt(purchases.length)}건의 매입 거래`,icon:'↙'},{label:'거래당 중앙값',n:med,unit:'money',desc:`평균 ${compactMoney(mean(vals)).join(' ')} · 모든 선택 거래`,icon:'◈'},{label:'선택한 거래',n:rows.length,unit:'count',desc:`${new Set(rows.map(r=>r.date)).size}개 거래일 · ${new Set(rows.map(r=>r.department)).size}개 부서`,icon:'▦'}];$('#kpi-grid').innerHTML=k.map(x=>{let [v,u]=x.unit==='money'?compactMoney(x.n):[fmt(x.n),'건'];return `<div class="kpi ${x.primary?'primary':''}"><div class="kpi-top"><span>${x.label}</span><span class="kpi-icon">${x.icon}</span></div><div class="kpi-value">${v}<small>${u}</small></div><div class="kpi-bottom">${esc(x.desc)}</div></div>`}).join('')}
function renderTrend(){const map=new Map();for(const r of state.rows){let key=r.date;if(state.period==='month')key=r.date.slice(0,7);if(state.period==='week'){let d=new Date(r.date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);key=d.toISOString().slice(0,10)}if(!map.has(key))map.set(key,{sales:0,purchases:0});map.get(key)[r.type==='매출'?'sales':'purchases']+=r.amount}let labels=[...map.keys()].sort();G.DashCharts.render($('#trend-chart'),{type:'line',labels,series:[{name:'매출',values:labels.map(k=>map.get(k).sales)},{name:'매입',values:labels.map(k=>map.get(k).purchases)}]},{height:275,label:'기간별 매출액과 매입액'});let sv=sum(state.rows.filter(r=>r.type==='매출').map(r=>r.amount)),pv=sum(state.rows.filter(r=>r.type==='매입').map(r=>r.amount));$('#trend-footnote').textContent=state.period==='week'?'주 시작일은 월요일입니다. 경계 주는 선택 기간에 속한 거래만 포함합니다.':`단위: 원 · 매출−매입 차액 ${fmt(sv-pv,'money')} · 이익 지표가 아닙니다.`}
function renderDepartments(){let totals={};for(const r of state.rows)totals[r.department]=(totals[r.department]||0)+r.amount;let items=Object.entries(totals).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value);G.DashCharts.horizontal($('#department-chart'),items);$('#department-insight').innerHTML=items.length?`<b>${esc(items[0].label)}</b> 부서가 선택한 거래금액의 <b>${fmt(items[0].value/sum(items.map(i=>i.value)),'percent')}</b>를 차지합니다.`:'선택한 조건에 해당하는 거래가 없습니다.'}
function renderDistribution(){let a=state.rows.map(r=>r.amount);if(!a.length){$('#distribution-chart').innerHTML='<div class="empty-chart">선택 데이터가 없습니다.</div>';$('#distribution-summary').innerHTML='';return}let min=Math.log10(Math.min(...a)),max=Math.log10(Math.max(...a));if(max===min)max=min+1;const bins=16,counts=Array(bins).fill(0),labels=Array.from({length:bins},(_,i)=>G.DashCharts.fmt(10**(min+(max-min)*i/bins)));a.forEach(v=>counts[Math.min(bins-1,Math.floor((Math.log10(v)-min)/(max-min)*bins))]++);G.DashCharts.render($('#distribution-chart'),{type:'bar',labels,series:[{name:'거래 건수',values:counts}]},{height:215,label:'로그 금액 구간별 거래 건수'});$('#distribution-summary').innerHTML=[['중앙값',quantile(a,.5)],['상위 10% 경계',quantile(a,.9)],['최대 거래금액',Math.max(...a)]].map(([k,v])=>`<div><small>${k}</small><strong>${compactMoney(v).join(' ')}</strong></div>`).join('')}
function renderCoverage(){const c=countStatuses(),parts=[['ok','#168a7f'],['limited','#e7b275'],['dropped','#d48b81'],['pending','#e8edef']];let offset=0;let arcs=parts.map(([s,color])=>{let len=c[s]/96*326.73;let arc=`<circle cx="70" cy="70" r="52" fill="none" stroke="${color}" stroke-width="10" stroke-dasharray="${len} ${326.73-len}" stroke-dashoffset="${-offset}" transform="rotate(-90 70 70)"/>`;offset+=len;return arc}).join('');$('#coverage-chart').innerHTML=`<div class="coverage-body"><svg class="coverage-ring" viewBox="0 0 140 140" aria-label="96개 중 ${96-c.pending}개 처리"><circle cx="70" cy="70" r="52" fill="none" stroke="#f0f4f5" stroke-width="10"/>${arcs}<text x="70" y="71" text-anchor="middle" fill="#25434e" font-size="29" font-weight="600">${96-c.pending}</text><text x="70" y="90" text-anchor="middle" fill="#9caab1" font-size="9">/ 96 ITEMS</text></svg><div class="coverage-list">${parts.map(([s,col])=>`<div><i style="background:${col}"></i>${statusName[s]}<b>${c[s]}</b></div>`).join('')}</div></div>`;$('#drop-nav').textContent=c.dropped}
function renderOverview(){renderKPIs();renderTrend();renderDepartments();renderDistribution();renderCoverage();renderFeatured()}
function resultFor(m){return state.results.get(m.id)||{id:m.id,status:'pending',summary:m.purpose,metrics:[]}}
// Previews reuse completed analysis outputs; they do not fit additional models.
function visualFor(m,r){
 if(r.status==='pending'||r.status==='dropped')return null;
 const rows=r.table?.rows||[],metric=i=>r.metrics?.[i]?.value;
 const bar=(labels,series,caption)=>({chart:{type:'bar',labels,series},caption});
 const series=(name,values)=>({name,values});
 const pair=row=>row[0]+' · '+row[1];
 const selectCaption=(text,n,total)=>text+(n<total?` · 표 순서 ${n}/${total}개`: '');
 if(r.chart){
  const captions={'01':'집단별 거래금액 · 원','02':'집단별 평균금액 · 원','03':'집단별 중앙값 · 원','04':'집단별 표준편차 · 원','05':'집단별 사분위 범위 · 원','06':'백분위별 경계금액 · 원','07':'log10(원) 구간별 거래 건수','08':'분위수 순서별 누적 비율 · 금액 간격 아님','09':'집단별 금액 분포 · 원','11':'두 범주 조합별 거래 건수','12':'상위 거래의 누적 금액 비중','13':'누적 거래 비율과 누적 금액 비율','14':'집단별 거래금액 지니계수','15':'월별 총액 변화의 두 효과 · 원'};
  return {chart:r.chart,caption:captions[m.id]||r.chart.title||'선택 데이터의 분석 결과'};
 }
 switch(m.id){
 case '10':{const top=[...rows].sort((a,b)=>b[2]-a[2]).slice(0,6);return bar(top.map(v=>v[0]),[series('거래금액',top.map(v=>v[2]))],`금액 상위 ${top.length}/${rows.length}개 층 · 원`)}
 case '18':case '19':{const row=rows[0];if(!row)return null;const isYuen=m.id==='19';return {chart:{type:'interval',points:[{label:row[0],value:metric(0),lo:row[isYuen?3:2],hi:row[isYuen?4:3]}]},caption:(isYuen?'절사평균':'평균')+' 차이와 95% 신뢰구간 · 원'}}
 case '21':{const show=rows.slice(0,6);return {chart:{type:'interval',points:show.map(v=>({label:pair(v),value:v[2],lo:v[6],hi:v[7]}))},caption:selectCaption('평균 차이와 동시 95% 구간 · 원',show.length,rows.length)}}
 case '22':return bar(['A 우세 + 동점 절반','그 외'],[series('비율',[metric(1),1-metric(1)])],'두 집단의 순위 우세 확률 · 합계 1');
 case '24':{const show=rows.slice(0,6);return bar(show.map(pair),[series('Dunn z',show.map(v=>v[2]))],selectCaption('쌍별 표준화 순위 차이',show.length,rows.length))}
 case '27':return bar(['관측 KS D'],[series('누적분포 최대 차이',[metric(0)])],'두 경험분포의 최대 차이 · D 범위 0–1');
 case '28':return bar(['관측 CvM'],[series('CvM 통계량',[metric(0)])],'계산된 CvM 검정통계량');
 case '32':return bar(rows.map(v=>v[0]),[series('카드',rows.map(v=>v[1])),series('그 외',rows.map(v=>v[2]))],'정확검정 대상 2×2 표 · 거래 건수');
 case '33':return bar(['관측 χ²'],[series('χ² 통계량',[metric(0)])],'Monte Carlo 검정의 관측 통계량');
 case '37':return {chart:{type:'heatmap',xLabels:r.table.headers.slice(1),yLabels:rows.map(v=>v[0]),matrix:rows.map(v=>v.slice(1))},caption:'부서별 거래 구분 × 카드 여부 · 건수'};
 case '38':return bar(rows.map(v=>v[0]),[series('포함 거래 수',rows.map(v=>v[2]))],'검정에 포함된 층별 거래 수 · 효과크기 아님');
 case '39':return {chart:{type:'scatter',diagonal:true,points:rows.map(v=>({label:v.slice(0,3).join(' · '),x:v[4],y:v[3]}))},caption:'가로: 독립모형 기대 건수 · 세로: 관측 건수'};
 case '87':return bar(rows.map(pair),[series('조건부 순열 p',rows.map(v=>v[2]))],'결과표에 보고된 집단 쌍의 순열 p값');
 case '88':return bar(rows.map(v=>v[0]),[series('평균',rows.map(v=>v[2])),series('중앙값',rows.map(v=>v[3]))],'집단별 평균금액과 중앙값 · 원');
 case '89':case '90':return bar(rows.map(pair),[series('원 p',rows.map(v=>v[2])),series(m.id==='89'?'Holm p':'BH q',rows.map(v=>v[3]))],'모든 집단 쌍의 보정 전·후 값 · 작을수록 낮은 p/q');
 default:return null;
 }
}
function cardHTML(m){let r=resultFor(m),metrics=(r.metrics||[]).slice(0,2),visual=visualFor(m,r);return `<button class="method-card" data-method="${m.id}" aria-label="${esc(m.name)} 그래프와 상세 결과"><div class="card-top"><span class="method-number">${m.id} / ${esc(shortCategories[m.category])}</span>${pill(r.status)}</div><h3>${esc(m.name)}</h3><p class="card-summary">${esc(r.summary||m.purpose)}</p>${visual?`<div class="card-visual"><div class="chart card-chart" data-preview="${m.id}"></div><div class="card-chart-caption">${esc(visual.caption)}</div></div>`:`<div class="card-chart-state ${r.status}"><span>${r.status==='dropped'?'분석에서 제외':'분석 대기 중'}</span><small>${r.status==='dropped'?'제외 사유는 상세 설명에서 확인하세요.':'계산이 끝나면 그래프가 표시됩니다.'}</small></div>`}<div class="card-metrics">${metrics.length?metrics.map(x=>`<div class="card-metric"><small>${esc(x.label)}</small><strong title="${esc(fmt(x.value,x.format))}">${esc(fmt(x.value,x.format))}</strong></div>`).join(''):`<div class="card-metric"><small>${r.status==='dropped'?'실행 상태':'분석 대상'}</small><strong style="font-size:12px">${r.status==='dropped'?'결과에서 제외':'현재 선택 거래'}</strong></div>`}</div><div class="card-bottom"><span>${r.status==='pending'?'실행 후 결과를 확인하세요':'크게 보기 · 상세 해석'}</span><span>↗</span></div></button>`}
function bindCards(root){root.querySelectorAll('[data-method]').forEach(el=>el.addEventListener('click',()=>showMethod(el.dataset.method)));root.querySelectorAll('[data-preview]').forEach(el=>{const m=D.catalog.find(x=>x.id===el.dataset.preview),visual=visualFor(m,resultFor(m));if(visual)G.DashCharts.render(el,visual.chart,{compact:true,width:340,height:185,label:m.name+' 결과 그래프'})})}
function renderFeatured(){let ids=['15','29','47'];$('#featured-methods').innerHTML=ids.map(id=>cardHTML(D.catalog.find(m=>m.id===id))).join('');bindCards($('#featured-methods'))}
function renderMethods(){let search=state.search.trim().toLowerCase();let matches=D.catalog.filter(m=>(state.category<0||m.category===state.category)&&(!search||(m.name+' '+m.purpose+' '+m.id).toLowerCase().includes(search))&&(state.status==='all'||resultFor(m).status===state.status));$('#method-grid').innerHTML=matches.length?matches.map(cardHTML).join(''):'<div class="empty-state">조건에 맞는 분석이 없습니다.<br>검색어 또는 상태 필터를 바꿔 주세요.</div>';$('#method-count').textContent=`${matches.length} / 96개 항목`;$$('#category-tabs button').forEach(b=>b.classList.toggle('active',+b.dataset.cat===state.category));$$('#category-nav button').forEach(b=>b.classList.toggle('selected',+b.dataset.cat===state.category));bindCards($('#method-grid'))}
function renderData(){const size=50,total=state.rows.length,maxPage=Math.max(0,Math.ceil(total/size)-1);state.page=Math.min(state.page,maxPage);let rows=state.rows.slice(state.page*size,(state.page+1)*size);$('#data-table-wrap').innerHTML=`<table><thead><tr><th>원본 행</th><th>거래일</th><th>구분</th><th>부서</th><th>결제수단</th><th class="money-cell">금액</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.id}</td><td>${r.date}</td><td><span class="type-tag ${r.type==='매입'?'purchase':''}">${r.type}</span></td><td>${esc(r.department)}</td><td>${esc(r.payment)}</td><td class="money-cell">${fmt(r.amount,'money')}</td></tr>`).join('')||'<tr><td colspan="6">선택한 데이터가 없습니다.</td></tr>'}</tbody></table>`;$('#data-page-info').textContent=`${state.page+1} / ${maxPage+1} 페이지 · ${fmt(total)}건`;$('#prev-page').disabled=state.page===0;$('#next-page').disabled=state.page>=maxPage}
function renderAudit(){let c=countStatuses();$('#audit-summary').innerHTML=Object.entries(c).map(([s,n])=>`<div><span>${statusName[s]}</span><b>${n}</b></div>`).join('');$('#audit-table').innerHTML=`<table><thead><tr><th>번호</th><th>분석 항목</th><th>상태</th><th>결과 또는 제외 사유</th></tr></thead><tbody>${D.catalog.map(m=>{let r=resultFor(m);return `<tr><td>${m.id}</td><td><button class="text-button" data-method="${m.id}">${esc(m.name)}</button></td><td>${pill(r.status)}</td><td style="min-width:260px;max-width:580px;line-height:1.8">${esc(r.summary||m.purpose)}</td></tr>`}).join('')}</tbody></table>`;bindCards($('#audit-table'));$('#source-details').textContent=`원본 ${D.meta.file} · ${D.meta.sheet}!${D.meta.range} · 데이터 ${fmt(D.meta.rows)}건 · 스냅샷 ${D.meta.packagedAt} · 마지막 실행 ${state.lastRun||'아직 없음'}. 원본 파일을 수정해도 이 스냅샷은 자동으로 바뀌지 않습니다.`}
function tableHTML(t){if(!t||!Array.isArray(t.headers)||!Array.isArray(t.rows))return '';let rows=t.rows.slice(0,200);return `<table><thead><tr>${t.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${(Array.isArray(row)?row:Object.values(row)).map(v=>`<td>${esc(typeof v==='number'?fmt(v):v)}</td>`).join('')}</tr>`).join('')}</tbody></table>${t.rows.length>200?'<p>표는 상위 200행을 표시합니다.</p>':''}`}
function showMethod(id){let m=D.catalog.find(x=>x.id===id);if(!m)return;let r=resultFor(m),visual=visualFor(m,r),chart=visual?.chart;$('#detail-id').textContent=`ANALYSIS ${m.id} / ${m.categoryName}`;$('#detail-title').textContent=m.name;$('#detail-content').innerHTML=`<div class="detail-intro">${pill(r.status)}<div><p>${esc(r.summary||m.purpose)}</p></div></div><div class="detail-section"><h3>무엇을 분석하나요</h3><p>${esc(m.purpose)}</p><p>${esc(r.explanation||'선택한 거래 데이터를 기준으로 이 항목을 계산합니다.')}</p></div>${r.status==='dropped'?`<div class="error-panel">이 기법은 이번 실행의 결과에서 제외했습니다.<br>${esc(r.error||r.reason||r.summary||'계산 조건을 만족하지 못했습니다.')}</div>`:''}${(r.metrics||[]).length?`<div class="detail-metrics">${r.metrics.map(x=>`<div><small>${esc(x.label)}</small><strong>${esc(fmt(x.value,x.format))}</strong></div>`).join('')}</div>`:''}${chart?'<div class="detail-chart-panel"><div class="chart-actions"><button class="text-button" id="save-chart">그래프 SVG 저장 ↓</button></div><div id="detail-chart" class="chart"></div></div>':''}${r.table?`<div class="detail-section"><h3>계산 결과</h3><div class="detail-table">${tableHTML(r.table)}</div></div>`:''}<div class="detail-section"><h3>적용 조건과 읽는 방법</h3><p>${esc(m.conditions)}</p>${(r.notes||[]).length?`<ul>${r.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul>`:''}</div><div class="detail-section"><h3>참고 자료</h3><div class="source-links">${m.sources.map(k=>D.sources[k]?`<a href="${esc(D.sources[k].url)}" target="_blank" rel="noopener noreferrer">${esc(D.sources[k].name)} ↗</a>`:`<span style="font-size:10px;color:#90a1aa">원장 데이터</span>`).join('')}</div></div><p class="detail-foot">선택 데이터 ${fmt(state.rows.length)}건 · 비교 기준 ${$('#group-filter').selectedOptions[0].text} · 실습용 가상 데이터 · 분석 실행 ${state.lastRun||'대기 중'}</p>`;if(!$('#method-dialog').open)$('#method-dialog').showModal();if(chart){try{G.DashCharts.render($('#detail-chart'),chart,{height:330,label:m.name+' 결과'});const caption=document.createElement('p');caption.className='detail-chart-caption';caption.textContent=visual.caption;$('#detail-chart').after(caption)}catch(e){$('#detail-chart').innerHTML='<div class="empty-chart">그래프를 표시할 수 없습니다. 수치와 결과표를 확인해 주세요.</div>'}$('#save-chart').addEventListener('click',()=>{let svg=$('#detail-chart svg');if(!svg)return toast('저장할 그래프가 없습니다.');download(`analysis-${id}.svg`,new XMLSerializer().serializeToString(svg),'image/svg+xml')})}}
function validateCard(r){if(!r||typeof r!=='object'||!r.id)return false;if(!['ok','limited','dropped'].includes(r.status))r.status='limited';if(!Array.isArray(r.metrics))r.metrics=[];if(!Array.isArray(r.notes))r.notes=[];if(r.status==='dropped'){r.reason=r.error||r.reason||r.notes[0]||r.summary;r.summary=r.reason}return true}
const assignments={core:D.catalog.filter(m=>+m.id<=41),models:D.catalog.filter(m=>(+m.id>=42&&+m.id<=55)||(+m.id>=75&&+m.id<=85)),temporal:D.catalog.filter(m=>(+m.id>=56&&+m.id<=74)||+m.id>=86)};
async function runAnalyses(){if(state.running)return;if(!filterRows())return;const seq=++state.runId;state.running=true;state.results=new Map();state.logs=[];state.lastRun=null;const start=performance.now();$('#apply-filters').disabled=true;$('#run-again').disabled=true;$('#run-progress').classList.remove('complete');$('#run-progress span').style.width='3%';$('#run-dot').style.background='#e7b275';renderOverview();renderMethods();renderData();renderAudit();const moduleNames=['core','models','temporal'],names={core:'분포·집단·범주 분석',models:'회귀·이상거래 분석',temporal:'시계열·검증 분석'};for(let i=0;i<moduleNames.length;i++){let key=moduleNames[i];$('#run-message').textContent=names[key]+' 계산 중…';await new Promise(res=>setTimeout(res,40));let t=performance.now();try{if(!state.rows.length)throw Error('선택 조건에 해당하는 거래가 없습니다.');const fn=G.DashboardModules?.[key];if(typeof fn!=='function')throw Error(`${key}.js 분석 모듈을 불러오지 못했습니다.`);const cards=await fn(state.rows,getCtx());if(!Array.isArray(cards))throw Error('분석 모듈이 결과 목록을 반환하지 않았습니다.');cards.forEach(r=>{if(validateCard(r))state.results.set(String(r.id).padStart(2,'0'),r)});for(const m of assignments[key])if(!state.results.has(m.id))state.results.set(m.id,{id:m.id,status:'dropped',summary:'분석 모듈이 이 항목의 결과를 반환하지 않아 제외했습니다.',notes:[],metrics:[]});state.logs.push({module:key,ms:Math.round(performance.now()-t),status:'complete'})}catch(error){for(const m of assignments[key])state.results.set(m.id,{id:m.id,status:'dropped',summary:'실행 실패: '+error.message,error:error.message,metrics:[],notes:['요청에 따라 실패한 기법은 이번 실행에서 제외했습니다.']});state.logs.push({module:key,ms:Math.round(performance.now()-t),status:'failed',error:error.message})}$('#run-progress span').style.width=((i+1)/moduleNames.length*100)+'%';renderCoverage();renderFeatured();if(state.view==='methods')renderMethods();if(state.view==='audit')renderAudit()}
state.running=false;state.lastRun=new Date().toLocaleString('ko-KR');$('#apply-filters').disabled=false;$('#run-again').disabled=false;$('#run-dot').style.background='#5fbaa4';let c=countStatuses();$('#run-message').textContent=`분석 완료 · ${c.ok}개 완료, ${c.limited}개 조건부, ${c.dropped}개 제외` ;$('#run-time').textContent=((performance.now()-start)/1000).toFixed(1)+'초';setTimeout(()=>{if(seq===state.runId)$('#run-progress').classList.add('complete')},700);renderMethods();renderAudit();renderFeatured();G.dispatchEvent(new CustomEvent('dashboard-ready',{detail:{statuses:c,ms:performance.now()-start}}))}
function csvCell(v){let s=String(v??'');if(/^[=+@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}
function download(name,content,type='text/csv;charset=utf-8'){let blob=new Blob([type.startsWith('text/csv')?'\ufeff':'',content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportResults(){if(!state.results.size)return toast('분석이 끝난 후 내보내 주세요.');let rows=[['번호','분야','기법','상태','요약','분석 설명','수치 결과','해석 조건','참고 및 제한']];for(let m of D.catalog){let r=resultFor(m);rows.push([m.id,m.categoryName,m.name,statusName[r.status],r.summary,r.explanation,(r.metrics||[]).map(x=>x.label+': '+fmt(x.value,x.format)).join(' / '),m.conditions,(r.notes||[]).join(' / ')])}download('거래원장_분석결과.csv',rows.map(r=>r.map(csvCell).join(',')).join('\r\n'));toast('분석 요약 CSV를 저장했습니다.')}
function init(){for(const [key,id] of [['department','department-filter'],['payment','payment-filter']]){let options=[...new Set(D.rows.map(r=>r[key]))].sort((a,b)=>a.localeCompare(b,'ko'));options.forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;$('#'+id).append(o)})}$('#date-from').min=$('#date-to').min=D.meta.minDate;$('#date-from').max=$('#date-to').max=D.meta.maxDate;$('#category-nav').innerHTML=shortCategories.map((name,i)=>`<button data-cat="${i}">${esc(name)}</button>`).join('');$('#category-tabs').innerHTML=[['전체',-1],...shortCategories.map((x,i)=>[x,i])].map(([name,i])=>`<button data-cat="${i}" class="${i===-1?'active':''}">${esc(name)}${i<0?' 96':''}</button>`).join('');$$('[data-cat]').forEach(b=>b.addEventListener('click',()=>{state.category=+b.dataset.cat;setView('methods')}));$$('.nav-item').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('.brand').addEventListener('click',e=>{e.preventDefault();setView('overview')});$$('[data-open-methods]').forEach(b=>b.addEventListener('click',()=>{state.category=-1;setView('methods')}));$$('[data-period]').forEach(b=>b.addEventListener('click',()=>{state.period=b.dataset.period;$$('[data-period]').forEach(x=>x.classList.toggle('active',x===b));renderTrend()}));$('#method-search').addEventListener('input',e=>{state.search=e.target.value;renderMethods()});$('#method-status').addEventListener('change',e=>{state.status=e.target.value;renderMethods()});$('#apply-filters').addEventListener('click',runAnalyses);$('#run-again').addEventListener('click',runAnalyses);$('#reset-filters').addEventListener('click',()=>{if(state.running)return;$('#date-from').value=D.meta.minDate;$('#date-to').value=D.meta.maxDate;['type-filter','department-filter','payment-filter'].forEach(id=>$('#'+id).value='');$('#group-filter').value='department';runAnalyses()});$('#prev-page').addEventListener('click',()=>{state.page--;renderData()});$('#next-page').addEventListener('click',()=>{state.page++;renderData()});$('#close-dialog').addEventListener('click',()=>$('#method-dialog').close());$('#method-dialog').addEventListener('click',e=>{if(e.target===$('#method-dialog')){let r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});$('#export-results').addEventListener('click',exportResults);$('#export-data').addEventListener('click',()=>download('선택_거래데이터.csv',[['원본 행','날짜','금액','매출/매입','부서','결제수단'],...state.rows.map(r=>[r.id,r.date,r.amount,r.type,r.department,r.payment])].map(r=>r.map(csvCell).join(',')).join('\r\n')));runAnalyses()}
init();
})(globalThis);
