"""Build portable static download pages from recipe folders (standard library only)."""
from pathlib import Path
from urllib.parse import quote
import html
import json
import re
import zipfile

ROOT = Path(__file__).resolve().parents[1]
RECIPES = ROOT / 'recipe'
MARKER = '<!-- Generated by scripts/build_recipes.py -->'
FOLDER = re.compile(r'^(?:recipe[ _-]*)?(\d+)$', re.IGNORECASE)


def esc(value):
    return html.escape(str(value), quote=True)


def write_page(path, content):
    if path.exists() and MARKER not in path.read_text(encoding='utf-8'):
        raise RuntimeError(f'Refusing to overwrite a non-generated page: {path}')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(MARKER + '\n' + content, encoding='utf-8', newline='\n')


def size_label(size):
    return f'{size / (1024 * 1024):.1f} MB' if size >= 1024 * 1024 else f'{max(1, round(size / 1024))} KB'


def shell(title, body, *, detail=False, script=False):
    prefix = '../' if detail else './'
    site_assets = '../../assets/' if detail else '../assets/'
    home = '../../index.html' if detail else '../index.html'
    back_url = '../index.html'
    back_text = '← 예제 파일 전체 보기' if detail else '← 실습 사이트로'
    return f'''<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)} · 아스트라 실습 자료</title>
  <meta name="description" content="책의 레시피별 예제 파일을 내려받고 아스트라 실습을 시작하세요.">
  <link rel="stylesheet" href="{prefix}assets/recipe.css">
  <link rel="stylesheet" href="{site_assets}site.css">
{f'  <script src="{prefix}assets/recipe.js" defer></script>' if script else ''}
</head>
<body>
  <a class="skip" href="#content">본문 바로가기</a>
  <div class="nana-site-header">
    <a class="nana-site-logo" href="https://nanalab.kr" aria-label="나나랩 홈페이지">
      <img src="https://nanalab.kr/logo.png" alt="NaNa Lab" width="2385" height="534" decoding="async">
    </a>
  </div>
  <nav class="nav" aria-label="주 메뉴"><div class="wrap">
    <a class="brand" href="{home}"><span>Astra</span> Playground</a>
    <a class="back" href="{back_url}">{back_text}</a>
  </div></nav>
  {body}
  <footer class="foot"><div class="wrap">Astra Playground · 레시피별 예제 파일
    <p class="nana-copyright">Copyright (c) <a href="https://bhban.kr">반병현</a> all right reserved.</p>
  </div></footer>
</body>
</html>
'''


def build():
    config = json.loads((RECIPES / 'catalog.json').read_text(encoding='utf-8'))
    titles = {}
    for key, title in config.get('titles', {}).items():
        if not str(key).isascii() or not str(key).isdigit() or int(key) < 1:
            raise ValueError(f'Invalid recipe number in catalog: {key}')
        titles[int(key)] = title
    sources = {}
    files = {}
    for folder in sorted(RECIPES.iterdir()):
        match = FOLDER.fullmatch(folder.name)
        if not folder.is_dir() or folder.is_symlink() or not match:
            continue
        number = int(match[1])
        if number < 1:
            raise ValueError(f'Recipe number must be positive: {folder.name}')
        sources.setdefault(number, []).append(folder)
        for path in sorted(folder.rglob('*')):
            relative = path.relative_to(folder)
            if not path.is_file() or path.is_symlink() or any(part.startswith('.') or part.startswith('~$') for part in relative.parts):
                continue
            if path == folder / 'index.html':
                continue
            if path.name.lower() in {'thumbs.db', 'desktop.ini'}:
                continue
            files.setdefault(number, []).append(path)

    # Only actual example files create recipes; titles alone do not create pages.
    # Gaps in numbering never create placeholder pages.
    numbers = sorted(files)
    count = len(numbers)

    # Validate all destinations before writing to protect hand-authored pages.
    destinations = [RECIPES / 'index.html']
    for number in numbers:
        destinations.append(RECIPES / f'{number:02}' / 'index.html')
        destinations.extend(folder / 'index.html' for folder in sources.get(number, []))
    for path in destinations:
        if path.exists() and MARKER not in path.read_text(encoding='utf-8'):
            raise RuntimeError(f'Refusing to overwrite a non-generated page: {path}')

    available = sum(bool(files.get(number)) for number in numbers)
    cards = []
    for position, number in enumerate(numbers):
        key = f'{number:02}'
        title = titles.get(number, '')
        items = files.get(number, [])
        full_title = f'레시피 {key}' + (f' · {title}' if title else '')
        search = ' '.join([full_title, *(path.name for path in items)])
        badge = f'{len(items)}개 파일' if items else '준비 중'
        description = ' · '.join(sorted(set(path.suffix[1:].upper() or 'FILE' for path in items))) if items else '예제 파일을 준비하고 있습니다.'
        cards.append(f'''<a class="recipe-card{' ready' if items else ''}" href="./{key}/index.html" data-recipe="{key}" data-available="{str(bool(items)).lower()}" data-search="{esc(search)}">
  <div class="card-top"><span class="number" aria-hidden="true">{key}</span><span class="badge">{badge}</span></div>
  <h2>{esc(full_title)}</h2><p>{esc(description)}</p>
  <span class="card-link">{'예제 파일 내려받기' if items else '레시피 페이지 보기'} <span aria-hidden="true">→</span></span>
</a>''')

        rows = []
        for path in items:
            ext = path.suffix[1:].upper() or 'FILE'
            href = '../' + quote(path.relative_to(RECIPES).as_posix(), safe='/')
            rows.append(f'''<article class="file">
  <span class="file-icon {esc(ext.lower())}" aria-hidden="true">{esc(ext)}</span>
  <div class="file-info"><h3>{esc(path.name)}</h3><p>{esc(ext)} · {size_label(path.stat().st_size)}</p></div>
  <a class="file-download" href="{href}" download="{esc(path.name)}" aria-label="{esc(path.name)} 다운로드">다운로드 <span aria-hidden="true">↓</span></a>
</article>''')

        archive = RECIPES / '_downloads' / f'recipe-{key}.zip'
        if items:
            archive.parent.mkdir(exist_ok=True)
            used = set()
            with zipfile.ZipFile(archive, 'w', compression=zipfile.ZIP_DEFLATED) as bundle:
                for path in items:
                    relative = path.relative_to(RECIPES)
                    arcname = Path(*relative.parts[1:]).as_posix()
                    if arcname in used:
                        arcname = relative.as_posix()
                    used.add(arcname)
                    info = zipfile.ZipInfo(arcname, date_time=(2026, 1, 1, 0, 0, 0))
                    info.compress_type = zipfile.ZIP_DEFLATED
                    bundle.writestr(info, path.read_bytes())
            downloads = f'''<div class="section-title"><h2>예제 파일 <span aria-hidden="true">·</span> {len(items)}개</h2>
  <a class="download-all" href="../_downloads/recipe-{key}.zip" download="레시피_{key}_예제파일.zip">전체 다운로드 (ZIP) <span aria-hidden="true">↓</span></a></div>
<div class="files">{''.join(rows)}</div>
<p class="help">필요한 파일을 각각 내려받거나, 전체 다운로드로 한 번에 받을 수 있습니다. ZIP 파일은 압축을 풀고 사용하세요.</p>'''
        else:
            if archive.exists():
                archive.unlink()
            downloads = '<div class="empty"><h2>예제 파일 준비 중</h2><p>자료가 등록되면 이 페이지에서 내려받을 수 있습니다.</p></div>'
        previous_number = numbers[position - 1] if position else None
        following_number = numbers[position + 1] if position + 1 < count else None
        previous = f'<a href="../{previous_number:02}/index.html">← 레시피 {previous_number:02}</a>' if previous_number is not None else '<span></span>'
        following = f'<a href="../{following_number:02}/index.html">레시피 {following_number:02} →</a>' if following_number is not None else '<span></span>'
        body = f'''<header class="hero"><div class="wrap"><p class="eyebrow">RECIPE {key} / DOWNLOAD</p>
<h1>{esc(full_title)}</h1><p>{'아래 파일을 내려받고 책의 순서에 따라 실습을 시작하세요.' if items else '이 레시피에서 사용하는 예제 파일을 모아 두는 곳입니다.'}</p></div></header>
<main id="content" class="wrap content">{downloads}<nav class="pager" aria-label="다른 레시피">{previous}<a href="../index.html">전체 목록</a>{following}</nav></main>'''
        page = shell(full_title, body, detail=True)
        write_page(RECIPES / key / 'index.html', page)
        # Preserve existing folders such as "recipe 04" and make them directly browsable too.
        for folder in sources.get(number, []):
            if folder.name != key:
                write_page(folder / 'index.html', page)

    body = f'''<header class="hero"><div class="wrap"><p class="eyebrow">RECIPE DOWNLOADS</p>
<h1>책을 펴고, 예제 파일을 내려받으세요.</h1>
<p>실습할 레시피 번호를 선택하세요.<br>필요한 파일만 골라 받거나 레시피별로 한 번에 받을 수 있습니다.</p>
<div class="stats"><span>등록된 레시피 <b>{count}</b>개</span><span>예제 파일 <b>{sum(map(len, files.values()))}</b>개</span></div></div></header>
<main id="content" class="wrap content">
<div class="toolbar"><label class="search" for="recipe-search">
<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg>
<input id="recipe-search" type="search" placeholder="레시피 번호, 제목, 파일명 검색" aria-label="레시피 검색"></label></div>
<p class="result" id="result-count" role="status" aria-live="polite">등록된 레시피 {count}개</p>
<div class="grid">{''.join(cards)}<div id="no-results" class="no-results"{' hidden' if count else ''}><h2>{'찾는 레시피가 없습니다.' if count else '예제 파일을 준비하고 있습니다.'}</h2><p>{'다른 번호나 검색어를 입력해 보세요.' if count else '자료가 등록되면 이곳에서 내려받을 수 있습니다.'}</p></div></div></main>'''
    write_page(RECIPES / 'index.html', shell('예제 파일 다운로드', body, script=True))
    # Remove only obsolete generated output; never remove example files or custom pages.
    for number, folders in sources.items():
        if number in numbers:
            continue
        for folder in folders:
            if not folder.resolve().is_relative_to(RECIPES.resolve()):
                raise RuntimeError(f'Folder escaped recipe directory: {folder}')
            page = folder / 'index.html'
            if page.is_file() and not page.is_symlink() and MARKER in page.read_text(encoding='utf-8'):
                page.unlink()
            if not any(folder.iterdir()):
                folder.rmdir()
        archive = RECIPES / '_downloads' / f'recipe-{number:02}.zip'
        if archive.is_file() and not archive.is_symlink():
            archive.unlink()
    print(f'Built {count} recipe pages; {available} available; {sum(map(len, files.values()))} files.')


if __name__ == '__main__':
    build()
