/* Offline descriptive, comparison and categorical statistics (inventory 01–41).
 * All inference is exploratory: no assumption of random or independent sampling.
 * A per-card exception becomes a dropped result; no replacement algorithm is run.
 */
(function (root) {
  'use strict';
  const sum = a => a.reduce((s, x) => s + x, 0);
  const mean = a => sum(a) / a.length;
  const sorted = a => a.slice().sort((a, b) => a - b);
  const variance = a => { const m = mean(a); return sum(a.map(x => (x - m) ** 2)) / (a.length - 1); };
  const quantile = (s, p) => { const h = (s.length - 1) * p, i = Math.floor(h); return s[i] + (s[Math.min(i + 1, s.length - 1)] - s[i]) * (h - i); };
  const clamp = (x, a = 0, b = 1) => Math.min(b, Math.max(a, x));
  const assert = (ok, message) => { if (!ok) throw new Error(message); };
  const metric = (label, value, format = 'number') => ({label, value, format});
  const fmt = n => new Intl.NumberFormat('ko-KR', {maximumFractionDigits: 0}).format(n);
  const group = (rows, key) => { const map = new Map(); for (const r of rows) { const k = typeof key === 'function' ? key(r) : r[key]; if (!map.has(k)) map.set(k, []); map.get(k).push(r); } return [...map].sort((a,b) => String(a[0]).localeCompare(String(b[0]), 'ko')); };
  const seriesChart = (type, labels, name, values) => ({type, labels, series:[{name, values}]});
  const rounded = (v, d = 4) => Number(v.toPrecision(Math.max(1, d + 1)));
  const interpretation = '유의확률은 거래가 독립 표본이라는 가정 아래의 탐색용 값입니다. 같은 날짜의 의존성·비무작위 관측·가상 데이터 생성 규칙은 보정하지 않았습니다.';
  function logGamma(z) {
    const c = [676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-0.13857109526572012,9.9843695780195716e-6,1.5056327351493116e-7];
    if (z < .5) return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);
    z -= 1; let x=.99999999999980993; for(let i=0;i<c.length;i++) x+=c[i]/(z+i+1);
    const t=z+c.length-.5; return .9189385332046727+(z+.5)*Math.log(t)-t+Math.log(x);
  }
  function gammaQ(a,x) {
    assert(a>0 && x>=0, '카이제곱 분포의 정의역을 만족하지 않습니다.');
    if(x===0) return 1;
    const front=Math.exp(-x+a*Math.log(x)-logGamma(a));
    if(x<a+1) { let term=1/a, s=term; for(let n=1;n<=500;n++){term*=x/(a+n);s+=term;if(Math.abs(term)<Math.abs(s)*1e-14) return clamp(1-front*s);} }
    else { let b=x+1-a,c=1e300,d=1/b,h=d; for(let i=1;i<=500;i++){const an=-i*(i-a);b+=2;d=an*d+b;if(Math.abs(d)<1e-300)d=1e-300;c=b+an/c;if(Math.abs(c)<1e-300)c=1e-300;d=1/d;const delta=d*c;h*=delta;if(Math.abs(delta-1)<1e-14)return clamp(front*h);} }
    throw new Error('불완전 감마함수가 수렴하지 않아 해당 검정을 제외했습니다.');
  }
  function betaCF(a,b,x) {
    const qab=a+b,qap=a+1,qam=a-1;let c=1,d=1-qab*x/qap;if(Math.abs(d)<1e-300)d=1e-300;d=1/d;let h=d;
    for(let m=1;m<=500;m++) { const m2=2*m; let aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<1e-300)d=1e-300;c=1+aa/c;if(Math.abs(c)<1e-300)c=1e-300;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<1e-300)d=1e-300;c=1+aa/c;if(Math.abs(c)<1e-300)c=1e-300;d=1/d;const delta=d*c;h*=delta;if(Math.abs(delta-1)<1e-14)return h; }
    throw new Error('불완전 베타함수가 수렴하지 않아 해당 검정을 제외했습니다.');
  }
  function betaI(x,a,b) { if(x<=0)return 0;if(x>=1)return 1;const bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log1p(-x));return clamp(x<(a+1)/(a+b+2)?bt*betaCF(a,b,x)/a:1-bt*betaCF(b,a,1-x)/b); }
  const tP = (t,df) => betaI(df/(df+t*t),df/2,.5);
  const fP = (f,d1,d2) => betaI(d2/(d2+d1*f),d2/2,d1/2);
  const chiP = (x,df) => gammaQ(df/2,x/2);
  function tCritical(df,alpha=.05){let lo=0,hi=1;while(tP(hi,df)>alpha&&hi<1e6)hi*=2;for(let i=0;i<60;i++){const m=(lo+hi)/2;if(tP(m,df)>alpha)lo=m;else hi=m;}return (lo+hi)/2;}
  function normalCDF(x) { const z=Math.abs(x),t=1/(1+.2316419*z),d=.3989422804014327*Math.exp(-z*z/2),tail=d*t*(.319381530+t*(-.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429)))); return x>=0?1-tail:tail; }
  const normalP = z => clamp(2*normalCDF(-Math.abs(z)));
  function rng(seed){let s=seed>>>0;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
  function normal(rand){return Math.sqrt(-2*Math.log(Math.max(1e-15,rand())))*Math.cos(2*Math.PI*rand());}
  function gammaSample(shape,rand){ if(shape<1)return gammaSample(shape+1,rand)*Math.max(1e-15,rand())**(1/shape);const d=shape-1/3,c=1/Math.sqrt(9*d);for(let i=0;i<1000;i++){const x=normal(rand),v=(1+c*x)**3;if(v<=0)continue;const u=rand();if(u<1-.0331*x**4||Math.log(u)<.5*x*x+d*(1-v+Math.log(v)))return d*v;}throw new Error('감마 난수 생성이 한도를 초과했습니다.');}
  function shuffle(a,rand){for(let i=a.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function rankData(arr) {const ids=arr.map((v,i)=>({v,i})).sort((a,b)=>a.v-b.v);const ranks=Array(arr.length);let ties=0;for(let i=0;i<ids.length;){let j=i+1;while(j<ids.length&&ids[j].v===ids[i].v)j++;const rank=(i+j+1)/2;for(let k=i;k<j;k++)ranks[ids[k].i]=rank;ties+=(j-i)**3-(j-i);i=j;}return {ranks,ties};}
  function holm(p){const o=p.map((p,i)=>({p,i})).sort((a,b)=>a.p-b.p),out=Array(p.length);let prior=0;o.forEach((v,j)=>{prior=Math.max(prior,Math.min(1,(p.length-j)*v.p));out[v.i]=prior;});return out;}
  function welch(a,b,trim=0) {
    function stats(x) { const s=sorted(x),g=Math.floor(s.length*trim),h=s.length-2*g;assert(h>=2,'절사 후 각 집단에 최소 2건이 필요합니다.');if(!g)return{m:mean(x),v:variance(x),n:x.length};const w=s.map((v,i)=>i<g?s[g]:i>=s.length-g?s[s.length-g-1]:v),wm=mean(w);return{m:mean(s.slice(g,s.length-g)),v:sum(w.map(v=>(v-wm)**2))/(h-1),n:h}; }
    const x=stats(a),y=stats(b),vx=x.v/x.n,vy=y.v/y.n,se=Math.sqrt(vx+vy);assert(se>0,'집단 내 분산이 0이어서 표준오차를 계산할 수 없습니다.');const df=(vx+vy)**2/(vx*vx/(x.n-1)+vy*vy/(y.n-1)),diff=x.m-y.m,t=diff/se,tc=tCritical(df);return{diff,se,df,t,p:tP(t,df),lo:diff-tc*se,hi:diff+tc*se,x,y};
  }
  function ordinaryAnova(groups) {const N=sum(groups.map(a=>a.length)),k=groups.length,grand=sum(groups.map(a=>sum(a)))/N;assert(k>=2&&N>k,'분산 분석의 집단 수 또는 표본 수가 부족합니다.');const ssb=sum(groups.map(a=>a.length*(mean(a)-grand)**2)),ssw=sum(groups.map(a=>{const m=mean(a);return sum(a.map(x=>(x-m)**2));}));assert(ssw>0,'집단 내 편차가 없어 F 검정을 계산할 수 없습니다.');const f=(ssb/(k-1))/(ssw/(N-k));return{f,p:fP(f,k-1,N-k),df1:k-1,df2:N-k};}
  function contingency(rows,rowKey,colKey){const r=[...new Set(rows.map(x=>typeof rowKey==='function'?rowKey(x):x[rowKey]))].sort(),c=[...new Set(rows.map(x=>typeof colKey==='function'?colKey(x):x[colKey]))].sort(),ri=new Map(r.map((v,i)=>[v,i])),ci=new Map(c.map((v,i)=>[v,i]));const cells=r.map(()=>c.map(()=>0));for(const x of rows)cells[ri.get(typeof rowKey==='function'?rowKey(x):x[rowKey])][ci.get(typeof colKey==='function'?colKey(x):x[colKey])]++;const rt=cells.map(sum),ct=c.map((_,j)=>sum(cells.map(a=>a[j]))),N=rows.length,expected=cells.map((a,i)=>a.map((_,j)=>rt[i]*ct[j]/N));let chi=0,small=0;cells.forEach((a,i)=>a.forEach((v,j)=>{chi+=(v-expected[i][j])**2/expected[i][j];if(expected[i][j]<5)small++;}));return{r,c,cells,rt,ct,N,expected,chi,small,df:(r.length-1)*(c.length-1)};}
  function binaryTypeTable(rows){return ['매출','매입'].map(type=>{const set=rows.filter(r=>r.type===type);return[set.filter(r=>r.payment==='카드').length,set.filter(r=>r.payment!=='카드').length];});}
  function fisher2x2(t){const [[a,b],[c,d]]=t,N=a+b+c+d,r=a+b,k=a+c;assert(r>0&&N-r>0&&k>0&&N-k>0,'2×2 표의 행·열 주변합이 모두 양수여야 합니다.');const logC=(n,k)=>logGamma(n+1)-logGamma(k+1)-logGamma(n-k+1),logp=x=>logC(k,x)+logC(N-k,r-x)-logC(N,r),observed=logp(a);let p=0;for(let x=Math.max(0,r-(N-k));x<=Math.min(r,k);x++){const lp=logp(x);if(lp<=observed+1e-10)p+=Math.exp(lp);}return clamp(p);}
  function odds(t){let [[a,b],[c,d]]=t;const corrected=Math.min(a,b,c,d)===0;if(corrected){a+=.5;b+=.5;c+=.5;d+=.5;}const log=Math.log(a*d/(b*c)),se=Math.sqrt(1/a+1/b+1/c+1/d);return{value:Math.exp(log),lo:Math.exp(log-1.96*se),hi:Math.exp(log+1.96*se),corrected};}
  function wilson(x,n){assert(n>0,'비율의 분모가 0입니다.');const p=x/n,z=1.959963984540054,a=1+z*z/n,c=(p+z*z/(2*n))/a,h=z/a*Math.sqrt(p*(1-p)/n+z*z/(4*n*n));return{p,lo:clamp(c-h),hi:clamp(c+h)};}
  function symmetricEigen(input){const a=input.map(x=>x.slice()),n=a.length,v=a.map((_,i)=>a.map((__,j)=>i===j?1:0));const scale=Math.max(1,...a.map((x,i)=>Math.abs(x[i])));let converged=false;for(let step=0;step<100*n*n;step++){let p=0,q=0,big=0;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(Math.abs(a[i][j])>big){big=Math.abs(a[i][j]);p=i;q=j;}if(big<scale*1e-12){converged=true;break;}const theta=.5*Math.atan2(2*a[p][q],a[q][q]-a[p][p]),c=Math.cos(theta),s=Math.sin(theta),app=a[p][p],aqq=a[q][q],apq=a[p][q];a[p][p]=c*c*app-2*s*c*apq+s*s*aqq;a[q][q]=s*s*app+2*s*c*apq+c*c*aqq;a[p][q]=a[q][p]=0;for(let j=0;j<n;j++){if(j!==p&&j!==q){const ap=a[j][p],aq=a[j][q];a[j][p]=a[p][j]=c*ap-s*aq;a[j][q]=a[q][j]=s*ap+c*aq;}const vp=v[j][p],vq=v[j][q];v[j][p]=c*vp-s*vq;v[j][q]=s*vp+c*vq;}}
    assert(converged,'대응분석의 고유값 분해가 수렴하지 않았습니다.');return a.map((_,i)=>({value:Math.max(0,a[i][i]),vector:v.map(row=>row[i])})).sort((a,b)=>b.value-a.value);}
  function validateCard(card){for(const m of card.metrics||[])if(typeof m.value==='number')assert(Number.isFinite(m.value),'계산 결과에 유한하지 않은 값이 있습니다.');return card;}

  root.DashboardModules=root.DashboardModules||{};
  root.DashboardModules.core=async function core(rows,ctx={}) {
    const cards=[],key=['department','payment','type'].includes(ctx.groupBy)?ctx.groupBy:'department',keyName={department:'부서',payment:'결제수단',type:'거래 구분'}[key],seed=ctx.seed||20261001;
    const amounts=rows.map(r=>r.amount),s=sorted(amounts),N=rows.length,gs=group(rows,key),stats=gs.map(([name,r])=>({name,rows:r,values:r.map(x=>x.amount),n:r.length,total:sum(r.map(x=>x.amount)),m:mean(r.map(x=>x.amount)),sd:r.length>1?Math.sqrt(variance(r.map(x=>x.amount))):0,q:sorted(r.map(x=>x.amount))})),labels=stats.map(x=>x.name),pair=stats.slice().sort((a,b)=>b.n-a.n||a.name.localeCompare(b.name,'ko')).slice(0,2);
    const pairNote=pair.length===2?`${keyName}별 건수가 많은 두 집단 ${pair[0].name}(${pair[0].n}건)과 ${pair[1].name}(${pair[1].n}건)을 비교했습니다. 효과 크기를 보고 고른 쌍은 아닙니다.`:'두 집단이 필요합니다.';
    const scopeNote=rows.some(r=>r.type==='매출')&&rows.some(r=>r.type==='매입')?'현재 매출·매입이 함께 선택되어 있습니다. 둘은 거래의 성격이 다르므로 구분 필터를 적용한 결과도 비교하세요.':'현재 선택한 거래 구분 범위의 분석입니다.';
    const base=(summary,explanation,metrics=[],extra={})=>({status:'ok',summary,explanation,metrics,notes:[],...extra});
    const infer=(summary,explanation,metrics=[],extra={})=>base(summary,explanation,metrics,{status:'limited',...extra,notes:[interpretation,...(extra.notes||[])]});
    const bar=(values,name)=>seriesChart('bar',labels,name,values);
    const two=()=>{assert(pair.length===2,'선택 범위에 비교 가능한 집단이 두 개 미만입니다.');assert(pair.every(x=>x.n>=2),'두 집단에 각각 최소 2건이 필요합니다.');return pair.map(x=>x.values);};
    const ctKey=key==='payment'?'department':'payment',ct=()=>contingency(rows,key,ctKey),ctChart=t=>({type:'heatmap',labels:t.c,series:[],xLabels:t.c,yLabels:t.r,matrix:t.cells});
    const methods={};
    methods['01']=()=>base(`선택된 ${fmt(N)}건의 거래 총액`, '양수로 기록된 거래금액을 더했습니다. 매출과 매입은 각각 표시하며 차액을 이익으로 간주하지 않습니다.',[metric('전체 거래금액',sum(amounts),'money'),...['매출','매입'].map(t=>metric(t,sum(rows.filter(r=>r.type===t).map(r=>r.amount)),'money'))],{chart:bar(stats.map(x=>x.total),'거래금액'),notes:[scopeNote]});
    methods['02']=()=>base(`거래당 평균 ${fmt(mean(amounts))}원`, '거래금액 합계를 거래 건수로 나눈 산술평균입니다. 초고액 거래에 민감하므로 중앙값과 함께 읽습니다.',[metric('평균',mean(amounts),'money'),metric('평균/중앙값',mean(amounts)/quantile(s,.5))],{chart:bar(stats.map(x=>x.m),'평균금액'),notes:[scopeNote]});
    methods['03']=()=>base(`거래 절반은 ${fmt(quantile(s,.5))}원 이하`, '정렬한 금액의 가운데 값으로 전형적인 거래 수준을 요약합니다. 전체 합계에 대한 기여도는 나타내지 않습니다.',[metric('중앙값',quantile(s,.5),'money')],{chart:bar(stats.map(x=>quantile(x.q,.5)),'중앙값')});
    methods['04']=()=>{assert(N>=2,'표준편차에는 최소 2건이 필요합니다.');return base('평균에서 벗어나는 금액의 크기', '표본 표준편차를 n−1 분모로 계산합니다. 분포가 치우친 경우 평균±표준편차를 정상 거래 범위로 해석하지 않습니다.',[metric('표본 표준편차',Math.sqrt(variance(amounts)),'money'),metric('변동계수',Math.sqrt(variance(amounts))/mean(amounts))],{chart:bar(stats.map(x=>x.sd),'표준편차')});};
    methods['05']=()=>base('거래 가운데 50%의 금액 구간', '선형 보간 분위수(Type 7)로 25·50·75% 지점을 구했습니다. 사분위 범위는 Q3−Q1입니다.',[metric('Q1',quantile(s,.25),'money'),metric('Q2',quantile(s,.5),'money'),metric('Q3',quantile(s,.75),'money'),metric('IQR',quantile(s,.75)-quantile(s,.25),'money')],{chart:bar(stats.map(x=>quantile(x.q,.75)-quantile(x.q,.25)),'사분위 범위')});
    methods['06']=()=>base('상위 고액 거래의 경계', '90·95·99번째 백분위수는 각각 약 10·5·1%의 거래가 초과하는 경계입니다. 값이 같은 거래 때문에 실제 초과 비중은 다를 수 있습니다.',[.9,.95,.99].map(p=>metric(`P${p*100}`,quantile(s,p),'money')),{chart:seriesChart('bar',['P50','P75','P90','P95','P99'],'경계금액',[.5,.75,.9,.95,.99].map(p=>quantile(s,p)))});
    methods['07']=()=>{const logs=s.map(x=>Math.log10(x));assert(logs.every(Number.isFinite),'양수가 아닌 금액은 로그 히스토그램에 적용할 수 없습니다.');const bins=18,lo=logs[0],hi=logs[logs.length-1],span=hi-lo||1,counts=Array(bins).fill(0),linear=Array(bins).fill(0),range=(s[s.length-1]-s[0])||1;for(const v of s){counts[Math.min(bins-1,Math.floor((Math.log10(v)-lo)/span*bins))]++;linear[Math.min(bins-1,Math.floor((v-s[0])/range*bins))]++;}return base('거래금액은 어떤 구간에 몰려 있는가', '차트는 log10(원) 구간의 빈도입니다. 원금액 등간격 히스토그램도 표에 함께 제시합니다.',[metric('거래 건수',N),metric('구간 수',bins)],{chart:seriesChart('bar',counts.map((_,i)=>(lo+i*span/bins).toFixed(1)),'로그금액 빈도',counts),table:{headers:['구간','원금액 하한','원금액 빈도','log10 하한','로그금액 빈도'],rows:counts.map((v,i)=>[i+1,Math.round(s[0]+i*range/bins),linear[i],(lo+i*span/bins).toFixed(2),v])},notes:['로그 차트의 가로축 6은 10⁶원(100만 원)을 의미합니다.']});};
    methods['08']=()=>{const thresholds=Array.from({length:41},(_,i)=>quantile(s,i/40)),lines=stats.map(g=>{let j=0;return{name:g.name,values:thresholds.map(v=>{while(j<g.q.length&&g.q[j]<=v)j++;return j/g.n;})};});return base('주어진 금액 이하인 거래의 비율', '집단별 경험적 누적분포(ECDF)입니다. 동일한 경계금액에서 선이 높을수록 그 금액 이하인 거래가 많습니다.',[metric('최소 금액',s[0],'money'),metric('최대 금액',s[s.length-1],'money')],{chart:{type:'line',labels:thresholds.map(v=>fmt(v)),series:lines},notes:['가로축은 전체 분포의 41개 분위수 지점을 순서대로 배치한 범주 축입니다. 동일 간격의 금액 축이 아닙니다.']});};
    methods['09']=()=>{const rr=stats.map(x=>{const q1=quantile(x.q,.25),q2=quantile(x.q,.5),q3=quantile(x.q,.75),iqr=q3-q1,inside=x.q.filter(v=>v>=q1-1.5*iqr&&v<=q3+1.5*iqr);return[x.name,inside[0],q1,q2,q3,inside[inside.length-1],x.n-inside.length];});return base('집단별 중앙값·산포·바깥 거래', '수염은 Q1−1.5×IQR부터 Q3+1.5×IQR 사이의 가장 먼 실제 관측까지 표시합니다. 범위 밖 건수는 오류 판정이 아닙니다.',[metric('집단 수',stats.length)],{chart:{type:'box',labels,series:['아래 수염','Q1','중앙값','Q3','위 수염'].map((name,j)=>({name,values:rr.map(r=>r[j+1])}))},table:{headers:[keyName,'아래 수염','Q1','중앙값','Q3','위 수염','바깥 건수'],rows:rr}});};
    methods['10']=()=>{const strat=group(rows,r=>`${r.type} / ${r.department} / ${r.date.slice(0,7)}`);return base('거래 구분·부서·월을 구분한 집계', '매출과 매입을 먼저 나눈 뒤 부서와 월 조합마다 건수·합계·평균·중앙값을 계산합니다.',[metric('층 조합 수',strat.length)],{table:{headers:['거래 구분 / 부서 / 월','건수','합계(원)','평균(원)','중앙값(원)'],rows:strat.map(([k,r])=>{const a=sorted(r.map(x=>x.amount));return[k,r.length,sum(a),Math.round(mean(a)),quantile(a,.5)];})}});};
    methods['11']=()=>{const t=ct();return base(`${keyName}와 ${ctKey==='payment'?'결제수단':'부서'}의 건수 교차표`, '각 셀은 두 범주의 조합에 해당하는 거래 건수입니다. 금액 합계로 만든 표가 아닙니다.',[metric('행 범주',t.r.length),metric('열 범주',t.c.length)],{chart:ctChart(t),table:{headers:[keyName,...t.c,'총 건수'],rows:t.r.map((r,i)=>[r,...t.cells[i],t.rt[i]])}});};
    methods['12']=()=>{const desc=s.slice().reverse(),total=sum(s),topN=Math.max(1,Math.ceil(N*.1));let cum=0;const ps=[.01,.05,.1,.2,.5,1],cumShares=ps.map(p=>sum(desc.slice(0,Math.ceil(N*p)))/total);for(let i=0;i<desc.length;i++){cum+=desc[i];if(cum>=total*.8){cum=i+1;break;}}return base(`상위 10% 거래가 총액의 ${(100*sum(desc.slice(0,topN))/total).toFixed(1)}% 차지`, '거래를 금액 내림차순으로 정렬해 상위 거래의 누적 금액 기여도를 계산했습니다.',[metric('상위 10% 금액 비중',sum(desc.slice(0,topN))/total,'percent'),metric('총액 80%에 필요한 거래 비율',cum/N,'percent')],{chart:seriesChart('line',ps.map(p=>`상위 ${p*100}%`),'누적 금액 비중',cumShares)},);};
    methods['13']=()=>{const types=group(rows,'type'),p=Array.from({length:21},(_,i)=>i/20);return base('작은 거래부터 누적한 금액의 집중', '가로축은 금액이 작은 순서의 누적 거래 비율, 세로축은 누적 금액 비율입니다. 대각선에서 아래로 멀어질수록 집중도가 높습니다.',[metric('총 거래 건수',N)],{chart:{type:'line',labels:p.map(x=>`${Math.round(x*100)}%`),series:[{name:'완전 균등',values:p},...types.map(([name,r])=>{const a=sorted(r.map(x=>x.amount)),total=sum(a),prefix=[0];a.forEach(v=>prefix.push(prefix[prefix.length-1]+v));return{name,values:p.map(x=>prefix[Math.floor(x*a.length)]/total)};})]}});};
    methods['14']=()=>{const gini=a=>{const v=sorted(a);return 2*sum(v.map((x,i)=>(i+1)*x))/(v.length*sum(v))-(v.length+1)/v.length;};return base(`거래금액 지니계수 ${gini(s).toFixed(3)}`, '모든 거래금액이 같으면 0에 가깝고 소수 거래에 집중될수록 1에 가까워집니다. 거래 기준 지니계수이며 고객 소득·고객 집중도를 측정한 값이 아닙니다.',[metric('전체 지니계수',gini(s))],{chart:bar(stats.map(x=>gini(x.values)),'지니계수')});};
    methods['15']=()=>{const months=group(rows,r=>r.date.slice(0,7));assert(months.length>=2,'월별 분해에는 서로 다른 두 달 이상이 필요합니다.');const out=[];for(const [type,tr] of group(rows,'type')){const m=group(tr,r=>r.date.slice(0,7));for(let i=1;i<m.length;i++){const prev=m[i-1],now=m[i],n0=prev[1].length,n1=now[1].length,a0=mean(prev[1].map(r=>r.amount)),a1=mean(now[1].map(r=>r.amount)),nc=(n1-n0)*(a0+a1)/2,ac=(a1-a0)*(n0+n1)/2;out.push([type,`${prev[0]} → ${now[0]}`,n1*a1-n0*a0,nc,ac]);}}assert(out.length,'동일 거래 구분에서 비교할 두 달이 없습니다.');return base('총액 증감을 건수와 평균금액으로 분해', '대칭 분해를 적용합니다. 건수 효과=건수 차이×두 달 평균금액의 평균, 금액 효과=평균금액 차이×두 달 건수의 평균. 두 효과의 합은 총액 변화와 같습니다.',[metric('비교 구간',out.length)],{chart:{type:'bar',labels:out.map(r=>`${r[0]} ${r[1]}`),series:[{name:'건수 효과',values:out.map(r=>r[3])},{name:'평균금액 효과',values:out.map(r=>r[4])}]},table:{headers:['구분','기간','총액 변화(원)','건수 효과(원)','평균금액 효과(원)'],rows:out}});};
    methods['16']=()=>{const months=group(rows,r=>r.date.slice(0,7));assert(months.length>=2,'구성비 표준화에는 두 달 이상이 필요합니다.');const details=[];for(const [type,tr] of group(rows,'type')){const byMonth=group(tr,r=>r.date.slice(0,7)),dept=group(tr,'department'),weights=new Map(dept.map(([d,r])=>[d,r.length/tr.length]));for(const [month,mr] of byMonth){const dmap=new Map(group(mr,'department'));assert([...weights.keys()].every(d=>dmap.has(d)),`${type}의 특정 월에 누락된 부서가 있어 동일 구성비 비교를 제외했습니다.`);const adj=sum([...weights].map(([d,w])=>w*mean(dmap.get(d).map(x=>x.amount))));details.push([type,month,mean(mr.map(x=>x.amount)),adj]);}}return base('부서 비중을 고정한 월별 평균금액', '거래 구분별 전체 기간의 거래 건수 비중을 공통 부서 가중치로 사용합니다. 각 월에 모든 부서가 관측된 경우만 정의되며 결과를 임의 보간하지 않습니다.',[metric('표준화 월×구분',details.length)],{chart:{type:'bar',labels:details.map(r=>`${r[0]} ${r[1]}`),series:[{name:'관측 평균',values:details.map(r=>r[2])},{name:'공통 구성비 평균',values:details.map(r=>r[3])}]},table:{headers:['구분','월','관측 평균(원)','표준화 평균(원)'],rows:details}});};
    methods['17']=()=>{const out=[];for(const [type,tr] of group(rows,'type')){const months=group(tr,r=>r.date.slice(0,7));for(let i=1;i<months.length;i++){const a=months[i-1],b=months[i],am=new Map(group(a[1],'department')),bm=new Map(group(b[1],'department')),deps=[...new Set([...am.keys(),...bm.keys()])];assert(deps.every(d=>am.has(d)&&bm.has(d)),`${type} 비교 월 중 부서가 누락되어 구성 효과를 식별할 수 없습니다.`);let composition=0,within=0;for(const d of deps){const a0=mean(am.get(d).map(r=>r.amount)),a1=mean(bm.get(d).map(r=>r.amount)),w0=am.get(d).length/a[1].length,w1=bm.get(d).length/b[1].length;composition+=(w1-w0)*(a0+a1)/2;within+=(a1-a0)*(w0+w1)/2;}out.push([type,`${a[0]} → ${b[0]}`,composition+within,composition,within]);}}assert(out.length,'동일 거래 구분에서 비교 가능한 월이 없습니다.');return base('평균 변화의 구성 효과와 부서 내부 효과', '대칭 Kitagawa 분해를 적용합니다. 부서 비중 변화와 부서 평균금액 변화의 교차항을 절반씩 배분하여 두 효과가 관측 평균 변화와 일치합니다.',[metric('분해 구간',out.length)],{chart:{type:'bar',labels:out.map(r=>`${r[0]} ${r[1]}`),series:[{name:'구성 변화',values:out.map(r=>r[3])},{name:'부서 내부 변화',values:out.map(r=>r[4])}]},table:{headers:['구분','월 비교','평균 변화(원)','구성 효과(원)','내부 효과(원)'],rows:out}});};
    methods['18']=()=>{const [a,b]=two(),t=welch(a,b);return infer('두 집단의 평균금액 차이', '집단별 분산과 표본 수를 따로 사용한 Welch t 검정입니다. 표시 구간은 평균 차이의 양측 95% t 신뢰구간입니다.',[metric('평균 차이',t.diff,'money'),metric('t',t.t),metric('자유도',t.df),metric('p',t.p,'pvalue')],{table:{headers:['방향','차이(원)','95% 하한','95% 상한'],rows:[[`${pair[0].name} − ${pair[1].name}`,t.diff,t.lo,t.hi]]},notes:[pairNote,scopeNote]});};
    methods['19']=()=>{const [a,b]=two(),t=welch(a,b,.2);return infer('양쪽 꼬리 20%를 절사한 중심 차이', 'Yuen 검정은 각 집단 양끝에서 floor(n×0.2)건씩 제거한 평균과 윈저화 분산을 사용합니다. 전체 산술평균에 대한 검정과 추정 대상이 다릅니다.',[metric('절사평균 차이',t.diff,'money'),metric('t',t.t),metric('자유도',t.df),metric('p',t.p,'pvalue')],{table:{headers:['방향','절사 후 n1','절사 후 n2','95% 하한','95% 상한'],rows:[[`${pair[0].name} − ${pair[1].name}`,t.x.n,t.y.n,t.lo,t.hi]]},notes:[pairNote]});};
    methods['20']=()=>{assert(stats.length>=2&&stats.every(g=>g.n>=2),'각 집단에 2건 이상이고 두 집단 이상이어야 합니다.');const k=stats.length,v=stats.map(g=>variance(g.values));assert(v.every(x=>x>0),'분산이 0인 집단이 있어 Welch ANOVA를 제외했습니다.');const w=stats.map((g,i)=>g.n/v[i]),W=sum(w),m=sum(w.map((x,i)=>x*stats[i].m))/W,A=sum(w.map((x,i)=>x*(stats[i].m-m)**2))/(k-1),B=sum(w.map((x,i)=>(1-x/W)**2/(stats[i].n-1))),f=A/(1+2*(k-2)*B/(k*k-1)),df2=(k*k-1)/(3*B);return infer('모든 집단의 평균이 같은지 비교', '이분산을 허용하는 Welch의 일원분산분석입니다. 유의한 결과가 나와도 어느 쌍이 다른지는 사후비교로 확인해야 합니다.',[metric('Welch F',f),metric('분자 자유도',k-1),metric('분모 자유도',df2),metric('p',fP(f,k-1,df2),'pvalue')],{chart:bar(stats.map(x=>x.m),'집단 평균'),notes:[scopeNote]});};
    methods['21']=()=>{assert(stats.length>=2&&stats.every(g=>g.n>=2),'각 집단에 2건 이상이어야 합니다.');const rand=rng(seed+21),B=999,k=stats.length,out=[];for(let i=0;i<k;i++)for(let j=i+1;j<k;j++){const t=welch(stats[i].values,stats[j].values),q=Math.SQRT2*Math.abs(t.t),samples=[];for(let b=0;b<B;b++){const z=Array.from({length:k},()=>normal(rand)),scale=Math.sqrt(2*gammaSample(t.df/2,rand)/t.df);samples.push((Math.max(...z)-Math.min(...z))/scale);}const p=(1+samples.filter(x=>x>=q).length)/(B+1),qc=quantile(sorted(samples),.95),half=qc*t.se/Math.SQRT2;out.push([stats[i].name,stats[j].name,t.diff,q,t.df,p,t.diff-half,t.diff+half]);}return infer('이분산을 고려한 모든 쌍의 평균 비교', 'Games–Howell의 쌍별 Welch 자유도와 studentized-range 분포를 사용했습니다. 해당 범위분포의 p와 임계값은 각 쌍 999회 Monte Carlo로 근사하며, 모든 집단 수를 사용해 다중비교를 반영합니다.',[metric('쌍 수',out.length),metric('쌍별 모의 횟수',B),metric('p 최소 해상도',1/(B+1),'pvalue')],{table:{headers:['집단 A','집단 B','평균 A−B(원)','q','df','근사 조정 p','동시 95% 하한','동시 95% 상한'],rows:out},notes:['정확한 수치적 studentized-range 적분이 아닌 난수 근사입니다. p가 0.05 부근이면 결론을 확정하지 마세요. 최대 Monte Carlo 표준오차는 약 0.016입니다.',`고정 시드 ${seed+21}`]});};
    methods['22']=()=>{const [a,b]=two(),n=a.length,m=b.length,N=n+m,{ranks,ties}=rankData([...a,...b]),U=sum(ranks.slice(0,n))-n*(n+1)/2,mu=n*m/2,v=n*m/12*(N+1-ties/(N*(N-1)));assert(v>0,'모든 값이 같아 순위 분산이 0입니다.');const z=Math.max(0,Math.abs(U-mu)-.5)/Math.sqrt(v);return infer('어느 집단에서 더 큰 금액이 관측되는가', 'Mann–Whitney U는 두 집단의 상대적 순위를 비교합니다. 동점 보정과 0.5 연속성 보정의 양측 정규근사 p를 계산했습니다.',[metric('U (집단 A)',U),metric('A가 B보다 클 확률+동점 절반',U/(n*m),'percent'),metric('p',normalP(z),'pvalue')],{notes:[pairNote,'분포 모양이 다르면 이 검정을 중앙값 차이만의 검정으로 해석할 수 없습니다. 작은 표본은 정규근사가 부정확할 수 있습니다.']});};
    methods['23']=()=>{assert(stats.length>=2,'순위 비교에 두 집단 이상이 필요합니다.');const all=stats.flatMap(x=>x.values),{ranks,ties}=rankData(all),total=all.length;let offset=0;const rankSums=stats.map(g=>{const v=sum(ranks.slice(offset,offset+g.n));offset+=g.n;return v;});const C=1-ties/(total**3-total);assert(C>0,'모든 금액이 같아 순위 검정을 적용할 수 없습니다.');const H=Math.max(0,(12/(total*(total+1))*sum(rankSums.map((v,i)=>v*v/stats[i].n))-3*(total+1))/C);return infer('집단별 금액 순위의 차이', 'Kruskal–Wallis의 동점 보정 H 통계량입니다. 귀무분포는 집단 수−1 자유도의 카이제곱으로 근사합니다.',[metric('H',H),metric('자유도',stats.length-1),metric('p',chiP(H,stats.length-1),'pvalue')],{chart:bar(rankSums.map((r,i)=>r/stats[i].n),'평균 순위'),notes:['한 집단이라도 표본이 적으면 카이제곱 근사에 주의해야 합니다.']});};
    methods['24']=()=>{assert(stats.length>=2,'Dunn 비교에 두 집단 이상이 필요합니다.');const all=stats.flatMap(x=>x.values),{ranks,ties}=rankData(all),total=all.length,A=total*(total+1)/12-ties/(12*(total-1));assert(A>0,'순위 분산이 0입니다.');let offset=0;const rmeans=stats.map(g=>{const r=mean(ranks.slice(offset,offset+g.n));offset+=g.n;return r;}),out=[];for(let i=0;i<stats.length;i++)for(let j=i+1;j<stats.length;j++){const z=(rmeans[i]-rmeans[j])/Math.sqrt(A*(1/stats[i].n+1/stats[j].n));out.push([stats[i].name,stats[j].name,z,normalP(z)]);}const adjusted=holm(out.map(r=>r[3]));return infer('모든 집단 쌍의 순위 차이와 Holm 보정', 'Dunn 검정의 전체 표본 순위·동점 보정 분산으로 각 쌍의 z를 구하고, 이 카드의 모든 쌍을 한 검정군으로 Holm 보정했습니다.',[metric('비교 쌍 수',out.length)],{table:{headers:['집단 A','집단 B','z','원 p','Holm p'],rows:out.map((r,i)=>[...r,adjusted[i]])},notes:['평균금액 차이를 검정하는 Games–Howell과 다른 질문입니다.']});};
    methods['25']=()=>{const transformed=stats.map(g=>g.values.map(v=>Math.abs(v-g.m))),a=ordinaryAnova(transformed);return infer('집단별 금액 변동성의 차이', '각 집단 평균에서의 절대편차를 구한 뒤 일원분산분석을 수행하는 평균 중심 Levene 검정입니다. 강한 왜도와 초고액 거래에 민감합니다.',[metric('Levene F',a.f),metric('p',a.p,'pvalue')],{chart:bar(transformed.map(mean),'평균 절대편차')});};
    methods['26']=()=>{const transformed=stats.map(g=>{const m=quantile(g.q,.5);return g.values.map(v=>Math.abs(v-m));}),a=ordinaryAnova(transformed);return infer('중앙값 기준으로 비교한 금액 변동성', '집단 중앙값에서의 절대편차에 ANOVA를 적용합니다. 이 카드는 중앙값 중심 Levene 검정인 Brown–Forsythe 산포 검정을 의미합니다.',[metric('Brown–Forsythe F',a.f),metric('p',a.p,'pvalue')],{chart:bar(transformed.map(mean),'중앙값에서의 평균 절대편차')});};
    function empiricalPermutation(kind){const [a,b]=two(),n=a.length,m=b.length,total=n+m,pooled=[...a.map(v=>({v,g:0})),...b.map(v=>({v,g:1}))].sort((a,b)=>a.v-b.v),blocks=[];for(let i=0;i<total;){let j=i+1;while(j<total&&pooled[j].v===pooled[i].v)j++;blocks.push([i,j]);i=j;}const original=pooled.map(v=>v.g),stat=lab=>{let na=0,nb=0,D=0,W=0;for(const [i,j]of blocks){for(let h=i;h<j;h++){if(lab[h]===0)na++;else nb++;}const diff=na/n-nb/m;D=Math.max(D,Math.abs(diff));W+=(j-i)*diff*diff;}return kind==='KS'?D:n*m/(total*total)*W;},observed=stat(original),rand=rng(seed+(kind==='KS'?27:28)),lab=Array.from({length:total},(_,i)=>i<n?0:1),B=499;let extreme=0;for(let b=0;b<B;b++){shuffle(lab,rand);if(stat(lab)>=observed-1e-12)extreme++;}const p=(extreme+1)/(B+1);return{observed,p,B,se:Math.sqrt(p*(1-p)/(B+1))};}
    methods['27']=()=>{const a=empiricalPermutation('KS');return infer('두 금액 분포 사이의 최대 누적비율 차이', '두 표본 Kolmogorov–Smirnov의 D를 계산하고 동점값을 유지한 499회 라벨 순열로 양측 p를 근사했습니다. 시간 의존성이 있으면 행 라벨의 교환가능성은 성립하지 않을 수 있습니다.',[metric('KS D',a.observed),metric('순열 p',a.p,'pvalue'),metric('Monte Carlo 표준오차',a.se)],{notes:[pairNote,`반복 ${a.B}회, 시드 ${seed+27}. 최소 p 해상도 0.002.`]});};
    methods['28']=()=>{const a=empiricalPermutation('CVM');return infer('금액 분포 전반의 누적 차이', '두 표본 Cramér–von Mises의 경험분포 적분형 통계량 nm/(n+m) × ∫(F−G)²dH를 계산했습니다. 동점에서는 우연속 CDF와 합동 경험측도의 질량을 사용하며 499회 순열로 이 통계량의 p를 보정합니다.',[metric('CvM 경험분포 통계량',a.observed),metric('순열 p',a.p,'pvalue'),metric('Monte Carlo 표준오차',a.se)],{notes:[pairNote,'동점값의 정의가 다른 연속분포용 순위 공식과 통계량 수치가 다를 수 있습니다. 이산 자료용 동일 통계량의 순열분포를 사용합니다.',`반복 ${a.B}회, 시드 ${seed+28}. 교환가능성을 가정합니다.`]});};
    methods['29']=()=>{const t=ct();assert(t.df>0,'교차표의 각 축에 두 범주 이상이 필요합니다.');return infer('두 범주형 변수의 독립성', '관측 건수와 주변합에서 계산한 독립 기대건수의 차이로 Pearson 카이제곱 통계량을 구했습니다. 기대빈도가 작은 셀이 많으면 근사가 불안정합니다.',[metric('χ²',t.chi),metric('자유도',t.df),metric('p',chiP(t.chi,t.df),'pvalue'),metric('기대건수 5 미만 셀',t.small)],{chart:ctChart(t),notes:[`전체 ${t.r.length*t.c.length}개 셀 중 기대빈도 5 미만 ${t.small}개.`]});};
    methods['30']=()=>{const t=ct();assert(t.df>0,'연관성 계산에 두 범주 이상의 행과 열이 필요합니다.');const V=Math.sqrt(t.chi/(t.N*Math.min(t.r.length-1,t.c.length-1)));return base('범주 간 연관성의 크기', 'Cramér’s V는 건수 교차표의 χ²를 표본 수와 표 크기로 정규화한 0~1 지표입니다. 연관성의 방향이나 인과효과를 나타내지 않습니다.',[metric('Cramér’s V',V),metric('거래 건수',N)],{chart:ctChart(t),notes:['편향 보정 없는 통상 정의입니다. 서로 다른 표 크기의 V를 고정 임계값 하나로 강·약 판정하지 않습니다.']});};
    methods['31']=()=>{const t=ct();assert(t.df>0,'표준화 잔차에 두 범주 이상의 행과 열이 필요합니다.');const matrix=t.cells.map((a,i)=>a.map((v,j)=>(v-t.expected[i][j])/Math.sqrt(t.expected[i][j]*(1-t.rt[i]/N)*(1-t.ct[j]/N)))),out=[];matrix.forEach((a,i)=>a.forEach((v,j)=>out.push([t.r[i],t.c[j],t.cells[i][j],t.expected[i][j],v])));return base('기대보다 많거나 적은 조합', '조정 표준화 잔차=(관측−기대)/√[기대×(1−행비율)×(1−열비율)]입니다. 양수는 독립 기대보다 많은 조합입니다.',[metric('최대 절대 잔차',Math.max(...matrix.flat().map(Math.abs)))],{chart:{...ctChart(t),matrix},table:{headers:[keyName,ctKey==='payment'?'결제수단':'부서','관측','기대','조정 표준화 잔차'],rows:out.sort((a,b)=>Math.abs(b[4])-Math.abs(a[4]))},notes:['여러 셀을 탐색하는 값으로 개별 |잔차|>1.96을 확정 유의 판정에 사용하지 않습니다.']});};
    methods['32']=()=>{const t=binaryTypeTable(rows),p=fisher2x2(t);return infer('매출·매입과 카드 사용 여부의 정확검정', '행은 매출/매입, 열은 카드/그 외 결제수단인 2×2 표입니다. 관측표보다 확률이 작거나 같은 고정 주변합 표의 초등분포 확률을 모두 합산한 양측 Fisher 정확 p입니다.',[metric('양측 정확 p',p,'pvalue')],{table:{headers:['구분','카드','그 외'],rows:[['매출',...t[0]],['매입',...t[1]]]},notes:['3가지 결제수단의 전체 관계가 아니라 카드/그 외로 정의한 별도의 질문입니다.']});};
    methods['33']=()=>{const t=ct();assert(t.df>0,'Monte Carlo 독립성 검정에 각 축 두 범주 이상이 필요합니다.');const ri=new Map(t.r.map((v,i)=>[v,i])),ci=new Map(t.c.map((v,i)=>[v,i])),a=rows.map(r=>ri.get(r[key])),b=rows.map(r=>ci.get(r[ctKey])),rand=rng(seed+33),B=499;let greater=0;for(let z=0;z<B;z++){shuffle(b,rand);const c=t.r.map(()=>t.c.map(()=>0));for(let i=0;i<N;i++)c[a[i]][b[i]]++;let chi=0;for(let i=0;i<t.r.length;i++)for(let j=0;j<t.c.length;j++)chi+=(c[i][j]-t.expected[i][j])**2/t.expected[i][j];if(chi>=t.chi-1e-10)greater++;}const p=(greater+1)/(B+1);return infer('주변합을 유지한 교차표 모의검정', '한 변수의 범주 라벨을 499회 순열하여 행·열 주변합을 고정한 Pearson χ² 귀무분포를 만들었습니다. 희소 셀에서도 점근 χ² 분포를 직접 사용하지 않습니다.',[metric('관측 χ²',t.chi),metric('Monte Carlo p',p,'pvalue'),metric('Monte Carlo 표준오차',Math.sqrt(p*(1-p)/(B+1)))],{notes:[`고정 시드 ${seed+33}. p 해상도는 0.002이며 행 단위 라벨 교환가능성을 가정합니다.`]});};
    methods['34']=()=>{const t=binaryTypeTable(rows),n0=sum(t[0]),n1=sum(t[1]);assert(n0>0&&n1>0,'비율 차이에 매출과 매입이 모두 필요합니다.');const a=wilson(t[0][0],n0),b=wilson(t[1][0],n1),d=a.p-b.p,lo=d-Math.sqrt((a.p-a.lo)**2+(b.hi-b.p)**2),hi=d+Math.sqrt((a.hi-a.p)**2+(b.p-b.lo)**2);return infer('매출 카드 비율 − 매입 카드 비율', '카드 거래 비중의 차이를 퍼센트포인트로 비교합니다. 95% 구간은 두 Wilson 구간을 결합한 Newcombe 독립 두 비율 차이 구간입니다.',[metric('비율 차이',d,'percent'),metric('95% 하한',lo,'percent'),metric('95% 상한',hi,'percent')],{chart:seriesChart('bar',['매출','매입'],'카드 비율',[a.p,b.p]),notes:['차이의 단위는 %p입니다. 상대 증가율이 아닙니다.']});};
    methods['35']=()=>{const groups=group(rows,'department'),out=groups.map(([name,r])=>{const w=wilson(r.filter(x=>x.payment==='카드').length,r.length);return[name,r.length,w.p,w.lo,w.hi];});return infer('부서별 카드 거래 비율과 추정 구간', '각 부서의 카드 건수/전체 건수에 Wilson 95% 신뢰구간을 계산했습니다. 0% 또는 100% 부서도 구간이 정의됩니다.',[metric('부서 수',out.length)],{chart:seriesChart('bar',out.map(r=>r[0]),'카드 비율',out.map(r=>r[2])),table:{headers:['부서','분모(건)','카드 비율','95% 하한','95% 상한'],rows:out},notes:['부서별 개별 95% 구간으로 전체 부서 동시 95% 구간은 아닙니다.']});};
    methods['36']=()=>{const t=binaryTypeTable(rows);assert(sum(t[0])>0&&sum(t[1])>0,'오즈비 비교에 매출과 매입이 모두 필요합니다.');const o=odds(t);return infer('매출 대 매입의 카드 사용 오즈비', '카드/그 외의 오즈를 매출과 매입에서 비교합니다. OR>1이면 매출의 카드 오즈가 더 크며, 카드 확률의 배율과는 다릅니다.',[metric('오즈비',o.value),metric('95% 하한',o.lo),metric('95% 상한',o.hi)],{table:{headers:['구분','카드','그 외'],rows:[['매출',...t[0]],['매입',...t[1]]]},notes:[o.corrected?'0인 셀이 있어 모든 셀에 0.5를 더한 Haldane–Anscombe 보정을 적용했습니다.':'로그 오즈비의 정규근사 95% 구간입니다.']});};
    methods['37']=()=>{const out=group(rows,'department').map(([d,r])=>{const t=binaryTypeTable(r);return[d,t[0][0],t[0][1],t[1][0],t[1][1]];});return base('부서별로 나눈 매출·매입과 카드 여부', '부서라는 층을 고정해 2×2 표를 각각 표시합니다. 전체에서 보이는 관계와 부서별 관계가 다를 수 있으므로 구조를 먼저 확인합니다.',[metric('부서 층 수',out.length)],{table:{headers:['부서','매출 카드','매출 그 외','매입 카드','매입 그 외'],rows:out}});};
    methods['38']=()=>{let numer=0,denom=0,orN=0,orD=0;const out=[];for(const[d,r]of group(rows,'department')){const [[a,b],[c,e]]=binaryTypeTable(r),n=a+b+c+e,row=a+b,col=a+c;const v=n>1?row*(n-row)*col*(n-col)/(n*n*(n-1)):0;if(v<=0){out.push([d,'정보 없는 층 제외',0]);continue;}numer+=a-row*col/n;denom+=v;orN+=a*e/n;orD+=b*c/n;out.push([d,'포함',n]);}assert(denom>0&&orD>0,'CMH에 정보가 있는 층이 없거나 공통 오즈비 분모가 0입니다.');const X=numer*numer/denom;return infer('부서를 고려한 카드 여부와 거래 구분의 관계', '연속성 보정 없는 Cochran–Mantel–Haenszel 1자유도 검정과 Mantel–Haenszel 공통 오즈비를 계산합니다. 정보가 없는 층은 검정 합계에서 제외됩니다.',[metric('CMH χ²',X),metric('p',chiP(X,1),'pvalue'),metric('MH 공통 오즈비',orN/orD)],{table:{headers:['부서','사용 여부','정보 있는 거래 수'],rows:out},notes:['공통 오즈비의 동질성을 검증하지 않았습니다. 부서별 효과 방향이 다르면 공통 오즈비만으로 요약하지 마세요.']});};
    methods['39']=()=>{const D=group(rows,'department'),P=group(rows,'payment'),T=group(rows,'type'),obs=new Map();for(const r of rows){const k=JSON.stringify([r.department,r.payment,r.type]);obs.set(k,(obs.get(k)||0)+1);}const out=[];let dev=0,pearson=0;for(const[d,dr]of D)for(const[p,pr]of P)for(const[t,tr]of T){const o=obs.get(JSON.stringify([d,p,t]))||0,e=dr.length*pr.length*tr.length/(N*N);dev+=o===0?2*e:2*(o*Math.log(o/e)-o+e);pearson+=(o-e)**2/e;out.push([d,p,t,o,e]);}const df=D.length*P.length*T.length-1-((D.length-1)+(P.length-1)+(T.length-1));assert(df>0,'완전 독립 로그선형 모형의 잔차 자유도가 없습니다.');return infer('부서·결제수단·거래 구분의 완전 독립 모형', 'Poisson 로그선형 모형 log(E)=상수+부서 효과+결제 효과+거래 구분 효과의 최대우도 적합값을 주변합의 곱으로 계산했습니다. 2·3원 상호작용은 포함하지 않은 [D][P][T] 모형입니다.',[metric('잔차 이탈도 G²',Math.max(0,dev)),metric('자유도',df),metric('적합도 p',chiP(Math.max(0,dev),df),'pvalue'),metric('Pearson χ²',pearson)],{table:{headers:['부서','결제수단','구분','관측 건수','독립모형 적합건수'],rows:out},notes:['작은 p는 이 완전 독립 모형이 관측표를 충분히 설명하지 못한다는 뜻입니다. 상호작용 모형의 최적 선택을 수행한 것은 아닙니다.']});};
    methods['40']=()=>{const t=ct();assert(t.df>0,'대응분석에 두 범주 이상의 행과 열이 필요합니다.');const rm=t.rt.map(x=>x/N),cm=t.ct.map(x=>x/N),A=t.cells.map((a,i)=>a.map((x,j)=>(x/N-rm[i]*cm[j])/Math.sqrt(rm[i]*cm[j]))),gram=t.c.map((_,j)=>t.c.map((__,k)=>sum(A.map(r=>r[j]*r[k])))),eig=symmetricEigen(gram),total=sum(eig.map(x=>x.value));assert(total>1e-14,'독립표의 총 관성이 0이어서 대응분석 축이 정의되지 않습니다.');const axes=eig.slice(0,2),points=[];for(let i=0;i<t.r.length;i++){const xy=axes.map(e=>sum(A[i].map((v,j)=>v*e.vector[j]))/Math.sqrt(rm[i]));points.push({x:xy[0]||0,y:xy[1]||0,label:`행 · ${t.r[i]}`});}for(let j=0;j<t.c.length;j++){const xy=axes.map(e=>Math.sqrt(e.value)*e.vector[j]/Math.sqrt(cm[j]));points.push({x:xy[0]||0,y:xy[1]||0,label:`열 · ${t.c[j]}`});}return base('건수 교차표를 두 축에 요약', '정규화된 독립 잔차 행렬의 특이값 분해에 해당하는 고유값 분해로 CA 주좌표를 계산했습니다. 축의 부호는 임의이며 희소 범주가 멀리 보일 수 있습니다.',[metric('1축 관성 비율',axes[0].value/total,'percent'),metric('2축 관성 비율',(axes[1]?.value||0)/total,'percent'),metric('총 관성',total)],{chart:{type:'scatter',labels:[],series:[],points},table:{headers:['범주','1축','2축'],rows:points.map(p=>[p.label,p.x,p.y])},notes:['행과 열 모두 주좌표인 대칭 지도입니다. 같은 범주 집합 내 거리를 비교하고 행-열 사이의 직접 거리로 관계 강도를 재지 않습니다.']});};
    methods['41']=()=>{const keys=['department','payment','type'],q=keys.length,categories=[],maps=keys.map(k=>{const vals=[...new Set(rows.map(r=>r[k]))].sort(),map=new Map();for(const v of vals){map.set(v,categories.length);categories.push({key:k,label:`${{department:'부서',payment:'결제',type:'구분'}[k]} · ${v}`,count:0});}return map;}),K=categories.length,co=Array.from({length:K},()=>Array(K).fill(0));for(const r of rows){const indices=keys.map((k,i)=>maps[i].get(r[k]));indices.forEach(i=>categories[i].count++);for(const i of indices)for(const j of indices)co[i][j]++;}const masses=categories.map(c=>c.count/(N*q)),gram=co.map((a,i)=>a.map((x,j)=>(x/(N*q*q)-masses[i]*masses[j])/Math.sqrt(masses[i]*masses[j]))),eig=symmetricEigen(gram),total=sum(eig.map(e=>e.value));assert(total>1e-14,'변수들이 모두 상수여서 MCA 관성이 없습니다.');const axes=eig.slice(0,2),points=categories.map((c,j)=>({label:c.label,x:Math.sqrt(axes[0].value)*axes[0].vector[j]/Math.sqrt(masses[j]),y:axes[1]?Math.sqrt(axes[1].value)*axes[1].vector[j]/Math.sqrt(masses[j]):0}));return base('세 범주형 변수의 공통 패턴 지도', '부서·결제수단·거래 구분의 완전 지시행렬에 대응분석을 적용한 MCA입니다. 범주 주좌표를 표시하고 관성 비율은 Benzécri 보정 없는 원 고유값을 사용했습니다.',[metric('범주 수',K),metric('1축 관성 비율',axes[0].value/total,'percent'),metric('2축 관성 비율',(axes[1]?.value||0)/total,'percent')],{chart:{type:'scatter',labels:[],series:[],points},table:{headers:['범주','1축','2축'],rows:points.map(p=>[p.label,p.x,p.y])},notes:['탐색적 요약입니다. 같은 변수의 범주들은 상호 배타적이며 가까운 점만으로 인과관계나 유의성을 주장할 수 없습니다.']});};
    // First review found invalid continuity-corrected odds on a structurally
    // constant filtered table. Per request, DROP rather than repair the method.
    methods['36']=()=>{throw new Error('초기 필터 검증에서 카드 여부에 변동이 없는 표에 잘못된 오즈비를 반환했습니다. 요청에 따라 보정·재구현 없이 이 기법을 제외했습니다.');};
    for(const [id,fn]of Object.entries(methods).sort((a,b)=>Number(a[0])-Number(b[0]))) {
      try {assert(N>0,'선택된 거래가 없습니다.');assert(amounts.every(x=>Number.isFinite(x)&&x>0),'양수의 유한한 금액만 지원합니다.');const card=validateCard(fn());if(card.chart?.type==='box')card.chart.boxes=card.chart.labels.map((label,i)=>({label,min:card.chart.series[0].values[i],q1:card.chart.series[1].values[i],median:card.chart.series[2].values[i],q3:card.chart.series[3].values[i],max:card.chart.series[4].values[i]}));cards.push({id,...card});}
      catch(error){cards.push({id,status:'dropped',summary:'분석에서 제외됨',explanation:'계산 오류 또는 적용 조건 불충족으로 이 기법을 중단했습니다. 다른 알고리즘으로 대체하지 않았습니다.',metrics:[],notes:[error.message||String(error)]});}
      if(Number(id)%8===0)await new Promise(resolve=>setTimeout(resolve,0));
    }
    return cards;
  };
})(typeof globalThis!=='undefined'?globalThis:window);
